title: Breve guia de sobrevivência com Terraform
description: Breve guia de sobrevivência com Terraform
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
